[project]
name = "pyairbyte-implementations"
version = "0.1.0"
description = ""
authors = [
    {name = "Mohamed Rilwan",email = "talk_to_rilwan@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "airbyte (>=0.35.5,<0.36.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
